import {
  TmsDefectInput,
  SmmsWorkInput,
  TdmsWorkInput,
  CoaTrainMovement,
  GoodsMovementForecast,
  BlockCorridorSection,
} from "./types";

// -------------------------------------------------------------
// SOURCE 1: TMS (Track Management System) — 18 Track Records
// -------------------------------------------------------------
export const CANONICAL_TMS_DEFECTS: TmsDefectInput[] = [
  {
    id: "TMS-1081",
    defectType: "Rail Joint Fracture",
    line: "DOWN",
    kmStart: 72.4,
    kmEnd: 72.9,
    depthMm: 6.2,
    severity: 5,
    overdueDays: 14,
    speedRestrictionKmph: 30,
    detectionMethod: "USFD Trolley",
    ingestedAt: "2026-09-18T01:15:00Z",
  },
  {
    id: "TMS-1082",
    defectType: "Thermite Weld Crack",
    line: "DOWN",
    kmStart: 73.1,
    kmEnd: 73.6,
    depthMm: 4.8,
    severity: 5,
    overdueDays: 12,
    speedRestrictionKmph: 45,
    detectionMethod: "USFD Trolley",
    ingestedAt: "2026-09-18T01:20:00Z",
  },
  {
    id: "TMS-1083",
    defectType: "Switch Blade Wear",
    line: "DOWN",
    kmStart: 75.8,
    kmEnd: 76.4,
    depthMm: 3.5,
    severity: 4,
    overdueDays: 7,
    detectionMethod: "Keyman Inspection",
    ingestedAt: "2026-09-18T02:00:00Z",
  },
  {
    id: "TMS-1084",
    defectType: "Gauge Spread",
    line: "DOWN",
    kmStart: 78.0,
    kmEnd: 79.2,
    severity: 4,
    overdueDays: 6,
    detectionMethod: "Track Recording Car",
    ingestedAt: "2026-09-18T02:10:00Z",
  },
  {
    id: "TMS-1085",
    defectType: "Sleeper Spalling",
    line: "DOWN",
    kmStart: 81.5,
    kmEnd: 82.8,
    severity: 3,
    overdueDays: 3,
    detectionMethod: "OMS-2000",
    ingestedAt: "2026-09-18T02:30:00Z",
  },
  {
    id: "TMS-1086",
    defectType: "USFD Flaw",
    line: "DOWN",
    kmStart: 84.1,
    kmEnd: 84.6,
    depthMm: 5.1,
    severity: 5,
    overdueDays: 11,
    speedRestrictionKmph: 30,
    detectionMethod: "USFD Trolley",
    ingestedAt: "2026-09-18T02:45:00Z",
  },
  {
    id: "TMS-1087",
    defectType: "Thermite Weld Crack",
    line: "DOWN",
    kmStart: 88.0,
    kmEnd: 88.5,
    severity: 3,
    overdueDays: 2,
    detectionMethod: "USFD Trolley",
    ingestedAt: "2026-09-18T03:00:00Z",
  },
  {
    id: "TMS-1088",
    defectType: "Gauge Spread",
    line: "DOWN",
    kmStart: 91.2,
    kmEnd: 92.4,
    severity: 3,
    overdueDays: 1,
    detectionMethod: "Track Recording Car",
    ingestedAt: "2026-09-18T03:15:00Z",
  },
  {
    id: "TMS-1089",
    defectType: "Rail Joint Fracture",
    line: "UP",
    kmStart: 18.2,
    kmEnd: 18.6,
    severity: 4,
    overdueDays: 8,
    detectionMethod: "USFD Trolley",
    ingestedAt: "2026-09-18T03:30:00Z",
  },
  {
    id: "TMS-1090",
    defectType: "Sleeper Spalling",
    line: "UP",
    kmStart: 21.0,
    kmEnd: 22.5,
    severity: 2,
    overdueDays: 0,
    detectionMethod: "OMS-2000",
    ingestedAt: "2026-09-18T03:40:00Z",
  },
  {
    id: "TMS-1091",
    defectType: "Switch Blade Wear",
    line: "BOTH",
    kmStart: 42.1,
    kmEnd: 42.6,
    severity: 4,
    overdueDays: 9,
    detectionMethod: "Keyman Inspection",
    ingestedAt: "2026-09-18T04:00:00Z",
  },
  {
    id: "TMS-1092",
    defectType: "USFD Flaw",
    line: "DOWN",
    kmStart: 46.0,
    kmEnd: 46.4,
    severity: 3,
    overdueDays: 2,
    detectionMethod: "USFD Trolley",
    ingestedAt: "2026-09-18T04:15:00Z",
  },
  {
    id: "TMS-1093",
    defectType: "Thermite Weld Crack",
    line: "DOWN",
    kmStart: 70.2,
    kmEnd: 70.8,
    severity: 4,
    overdueDays: 5,
    detectionMethod: "USFD Trolley",
    ingestedAt: "2026-09-18T04:30:00Z",
  },
  {
    id: "TMS-1094",
    defectType: "Gauge Spread",
    line: "DOWN",
    kmStart: 74.0,
    kmEnd: 75.0,
    severity: 3,
    overdueDays: 2,
    detectionMethod: "Track Recording Car",
    ingestedAt: "2026-09-18T04:45:00Z",
  },
  {
    id: "TMS-1095",
    defectType: "Sleeper Spalling",
    line: "DOWN",
    kmStart: 77.2,
    kmEnd: 78.4,
    severity: 2,
    overdueDays: 0,
    detectionMethod: "OMS-2000",
    ingestedAt: "2026-09-18T05:00:00Z",
  },
  {
    id: "TMS-1096",
    defectType: "Rail Joint Fracture",
    line: "DOWN",
    kmStart: 80.1,
    kmEnd: 80.5,
    severity: 4,
    overdueDays: 7,
    detectionMethod: "USFD Trolley",
    ingestedAt: "2026-09-18T05:10:00Z",
  },
  {
    id: "TMS-1097",
    defectType: "Switch Blade Wear",
    line: "DOWN",
    kmStart: 86.3,
    kmEnd: 86.9,
    severity: 3,
    overdueDays: 1,
    detectionMethod: "Keyman Inspection",
    ingestedAt: "2026-09-18T05:20:00Z",
  },
  {
    id: "TMS-1098",
    defectType: "Thermite Weld Crack",
    line: "DOWN",
    kmStart: 93.0,
    kmEnd: 93.5,
    severity: 3,
    overdueDays: 2,
    detectionMethod: "USFD Trolley",
    ingestedAt: "2026-09-18T05:30:00Z",
  },
];

// -------------------------------------------------------------
// SOURCE 2: SMMS (Signal Maintenance Management System) — 14 Records
// -------------------------------------------------------------
export const CANONICAL_SMMS_WORK: SmmsWorkInput[] = [
  {
    id: "SMMS-421",
    assetType: "Point Machine",
    assetId: "PM-72.8-DN",
    stationCode: "WL",
    kmLocation: 72.8,
    line: "DOWN",
    maintenanceType: "Periodic Overhaul",
    durationMin: 35,
    overdueDays: 8,
    criticality: "Critical",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T01:30:00Z",
  },
  {
    id: "SMMS-422",
    assetType: "Track Circuit",
    assetId: "TC-74.2-DN",
    stationCode: "WL",
    kmLocation: 74.2,
    line: "DOWN",
    maintenanceType: "Insulation Resistance Test",
    durationMin: 25,
    overdueDays: 4,
    criticality: "High",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T01:45:00Z",
  },
  {
    id: "SMMS-423",
    assetType: "Multi-Aspect Signal",
    assetId: "SIG-76.0-DN",
    stationCode: "KCG",
    kmLocation: 76.0,
    line: "DOWN",
    maintenanceType: "Contact Cleaning",
    durationMin: 20,
    overdueDays: 3,
    criticality: "High",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T02:15:00Z",
  },
  {
    id: "SMMS-424",
    assetType: "Axle Counter",
    assetId: "AC-78.5-DN",
    stationCode: "KCG",
    kmLocation: 78.5,
    line: "DOWN",
    maintenanceType: "Cable Meggering",
    durationMin: 30,
    overdueDays: 1,
    criticality: "Medium",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T02:40:00Z",
  },
  {
    id: "SMMS-425",
    assetType: "Point Machine",
    assetId: "PM-83.1-DN",
    stationCode: "KCG",
    kmLocation: 83.1,
    line: "DOWN",
    maintenanceType: "Obstruction Test",
    durationMin: 25,
    overdueDays: 5,
    criticality: "High",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T03:00:00Z",
  },
  {
    id: "SMMS-426",
    assetType: "Track Circuit",
    assetId: "TC-86.4-DN",
    stationCode: "NDKD",
    kmLocation: 86.4,
    line: "DOWN",
    maintenanceType: "Periodic Overhaul",
    durationMin: 35,
    overdueDays: 2,
    criticality: "Medium",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T03:20:00Z",
  },
  {
    id: "SMMS-427",
    assetType: "Multi-Aspect Signal",
    assetId: "SIG-90.2-DN",
    stationCode: "NDKD",
    kmLocation: 90.2,
    line: "DOWN",
    maintenanceType: "Contact Cleaning",
    durationMin: 20,
    overdueDays: 0,
    criticality: "Medium",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T03:45:00Z",
  },
  {
    id: "SMMS-428",
    assetType: "Point Machine",
    assetId: "PM-19.4-UP",
    stationCode: "SEC",
    kmLocation: 19.4,
    line: "UP",
    maintenanceType: "Periodic Overhaul",
    durationMin: 40,
    overdueDays: 6,
    criticality: "High",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T04:00:00Z",
  },
  {
    id: "SMMS-429",
    assetType: "Axle Counter",
    assetId: "AC-22.1-UP",
    stationCode: "SEC",
    kmLocation: 22.1,
    line: "UP",
    maintenanceType: "Cable Meggering",
    durationMin: 25,
    overdueDays: 1,
    criticality: "Low",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T04:15:00Z",
  },
  {
    id: "SMMS-430",
    assetType: "Multi-Aspect Signal",
    assetId: "SIG-43.0-BOTH",
    stationCode: "KZJ",
    kmLocation: 43.0,
    line: "BOTH",
    maintenanceType: "Periodic Overhaul",
    durationMin: 30,
    overdueDays: 7,
    criticality: "High",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T04:30:00Z",
  },
  {
    id: "SMMS-431",
    assetType: "Track Circuit",
    assetId: "TC-71.5-DN",
    stationCode: "WL",
    kmLocation: 71.5,
    line: "DOWN",
    maintenanceType: "Insulation Resistance Test",
    durationMin: 20,
    overdueDays: 3,
    criticality: "Medium",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T04:45:00Z",
  },
  {
    id: "SMMS-432",
    assetType: "Point Machine",
    assetId: "PM-77.0-DN",
    stationCode: "KCG",
    kmLocation: 77.0,
    line: "DOWN",
    maintenanceType: "Obstruction Test",
    durationMin: 25,
    overdueDays: 4,
    criticality: "High",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T05:00:00Z",
  },
  {
    id: "SMMS-433",
    assetType: "Multi-Aspect Signal",
    assetId: "SIG-82.0-DN",
    stationCode: "KCG",
    kmLocation: 82.0,
    line: "DOWN",
    maintenanceType: "Contact Cleaning",
    durationMin: 20,
    overdueDays: 1,
    criticality: "Medium",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T05:15:00Z",
  },
  {
    id: "SMMS-434",
    assetType: "Axle Counter",
    assetId: "AC-89.5-DN",
    stationCode: "NDKD",
    kmLocation: 89.5,
    line: "DOWN",
    maintenanceType: "Cable Meggering",
    durationMin: 30,
    overdueDays: 2,
    criticality: "Medium",
    requiresPowerIsolation: false,
    ingestedAt: "2026-09-18T05:30:00Z",
  },
];

// -------------------------------------------------------------
// SOURCE 3: TDMS (Traction Distribution Management System) — 15 Records
// -------------------------------------------------------------
export const CANONICAL_TDMS_WORK: TdmsWorkInput[] = [
  {
    id: "TDMS-881",
    assetType: "Cantilever Assembly",
    substationCode: "TSS-WL-01",
    oheSectionId: "OHE-SEC-WL-DN",
    kmStart: 73.0,
    kmEnd: 73.5,
    line: "DOWN",
    workType: "Height & Stagger Adjustment",
    durationMin: 30,
    powerBlockRequired: true,
    overdueDays: 9,
    criticality: "Critical",
    ingestedAt: "2026-09-18T01:10:00Z",
  },
  {
    id: "TDMS-882",
    assetType: "Contact Wire",
    substationCode: "TSS-WL-01",
    oheSectionId: "OHE-SEC-WL-DN",
    kmStart: 74.5,
    kmEnd: 75.8,
    line: "DOWN",
    workType: "Contact Wire Dropper Renewal",
    durationMin: 45,
    powerBlockRequired: true,
    overdueDays: 11,
    criticality: "Critical",
    ingestedAt: "2026-09-18T01:30:00Z",
  },
  {
    id: "TDMS-883",
    assetType: "Section Insulator",
    substationCode: "TSS-KCG-02",
    oheSectionId: "OHE-WL-KCG-DN",
    kmStart: 77.4,
    kmEnd: 77.8,
    line: "DOWN",
    workType: "Insulator De-greasing",
    durationMin: 25,
    powerBlockRequired: true,
    overdueDays: 5,
    criticality: "High",
    ingestedAt: "2026-09-18T02:00:00Z",
  },
  {
    id: "TDMS-884",
    assetType: "Auto Tensioning Device (ATD)",
    substationCode: "TSS-KCG-02",
    oheSectionId: "OHE-WL-KCG-DN",
    kmStart: 80.2,
    kmEnd: 80.8,
    line: "DOWN",
    workType: "Current Collection Test",
    durationMin: 35,
    powerBlockRequired: true,
    overdueDays: 4,
    criticality: "High",
    ingestedAt: "2026-09-18T02:20:00Z",
  },
  {
    id: "TDMS-885",
    assetType: "Catenary Wire",
    substationCode: "TSS-NDKD-03",
    oheSectionId: "OHE-KCG-NDKD-DN",
    kmStart: 85.0,
    kmEnd: 86.2,
    line: "DOWN",
    workType: "Thermal Imaging Audit",
    durationMin: 40,
    powerBlockRequired: true,
    overdueDays: 2,
    criticality: "Medium",
    ingestedAt: "2026-09-18T02:50:00Z",
  },
  {
    id: "TDMS-886",
    assetType: "Cantilever Assembly",
    substationCode: "TSS-NDKD-03",
    oheSectionId: "OHE-KCG-NDKD-DN",
    kmStart: 88.5,
    kmEnd: 89.0,
    line: "DOWN",
    workType: "Height & Stagger Adjustment",
    durationMin: 25,
    powerBlockRequired: true,
    overdueDays: 1,
    criticality: "Medium",
    ingestedAt: "2026-09-18T03:15:00Z",
  },
  {
    id: "TDMS-887",
    assetType: "Section Insulator",
    substationCode: "TSS-NDKD-03",
    oheSectionId: "OHE-KCG-NDKD-DN",
    kmStart: 92.1,
    kmEnd: 92.6,
    line: "DOWN",
    workType: "Insulator De-greasing",
    durationMin: 20,
    powerBlockRequired: true,
    overdueDays: 0,
    criticality: "Low",
    ingestedAt: "2026-09-18T03:30:00Z",
  },
  {
    id: "TDMS-888",
    assetType: "Contact Wire",
    substationCode: "TSS-SEC-01",
    oheSectionId: "OHE-SEC-KZJ-UP",
    kmStart: 17.5,
    kmEnd: 18.8,
    line: "UP",
    workType: "Contact Wire Dropper Renewal",
    durationMin: 45,
    powerBlockRequired: true,
    overdueDays: 7,
    criticality: "High",
    ingestedAt: "2026-09-18T03:50:00Z",
  },
  {
    id: "TDMS-889",
    assetType: "Auto Tensioning Device (ATD)",
    substationCode: "TSS-SEC-01",
    oheSectionId: "OHE-SEC-KZJ-UP",
    kmStart: 20.4,
    kmEnd: 21.0,
    line: "UP",
    workType: "Current Collection Test",
    durationMin: 30,
    powerBlockRequired: true,
    overdueDays: 3,
    criticality: "Medium",
    ingestedAt: "2026-09-18T04:10:00Z",
  },
  {
    id: "TDMS-890",
    assetType: "Feeding Post",
    substationCode: "TSS-KZJ-01",
    oheSectionId: "OHE-KZJ-WL-BOTH",
    kmStart: 41.5,
    kmEnd: 42.0,
    line: "BOTH",
    workType: "Height & Stagger Adjustment",
    durationMin: 35,
    powerBlockRequired: true,
    overdueDays: 8,
    criticality: "High",
    ingestedAt: "2026-09-18T04:30:00Z",
  },
  {
    id: "TDMS-891",
    assetType: "Cantilever Assembly",
    substationCode: "TSS-WL-01",
    oheSectionId: "OHE-SEC-WL-DN",
    kmStart: 71.0,
    kmEnd: 71.6,
    line: "DOWN",
    workType: "Height & Stagger Adjustment",
    durationMin: 25,
    powerBlockRequired: true,
    overdueDays: 4,
    criticality: "Medium",
    ingestedAt: "2026-09-18T04:50:00Z",
  },
  {
    id: "TDMS-892",
    assetType: "Section Insulator",
    substationCode: "TSS-WL-01",
    oheSectionId: "OHE-SEC-WL-DN",
    kmStart: 75.0,
    kmEnd: 75.4,
    line: "DOWN",
    workType: "Insulator De-greasing",
    durationMin: 20,
    powerBlockRequired: true,
    overdueDays: 3,
    criticality: "Medium",
    ingestedAt: "2026-09-18T05:05:00Z",
  },
  {
    id: "TDMS-893",
    assetType: "Contact Wire",
    substationCode: "TSS-KCG-02",
    oheSectionId: "OHE-WL-KCG-DN",
    kmStart: 79.0,
    kmEnd: 80.0,
    line: "DOWN",
    workType: "Contact Wire Dropper Renewal",
    durationMin: 35,
    powerBlockRequired: true,
    overdueDays: 2,
    criticality: "Medium",
    ingestedAt: "2026-09-18T05:20:00Z",
  },
  {
    id: "TDMS-894",
    assetType: "Catenary Wire",
    substationCode: "TSS-KCG-02",
    oheSectionId: "OHE-WL-KCG-DN",
    kmStart: 82.5,
    kmEnd: 83.2,
    line: "DOWN",
    workType: "Thermal Imaging Audit",
    durationMin: 30,
    powerBlockRequired: true,
    overdueDays: 1,
    criticality: "Low",
    ingestedAt: "2026-09-18T05:35:00Z",
  },
  {
    id: "TDMS-895",
    assetType: "Cantilever Assembly",
    substationCode: "TSS-NDKD-03",
    oheSectionId: "OHE-KCG-NDKD-DN",
    kmStart: 87.0,
    kmEnd: 87.6,
    line: "DOWN",
    workType: "Height & Stagger Adjustment",
    durationMin: 25,
    powerBlockRequired: true,
    overdueDays: 2,
    criticality: "Medium",
    ingestedAt: "2026-09-18T05:50:00Z",
  },
];

// -------------------------------------------------------------
// SOURCE 4: COA (Control Office Application) Timetable — 8 Trains
// -------------------------------------------------------------
export const CANONICAL_COA_TIMETABLE: CoaTrainMovement[] = [
  {
    trainId: "VB-20612",
    serviceNumber: "20612",
    trainName: "Vande Bharat Express",
    trainType: "Vande Bharat",
    priorityClass: 1,
    direction: "DOWN",
    stops: [
      { stationCode: "SEC", km: 40, arrivalMins: 140, departureMins: 140, dwellMin: 0 },
      { stationCode: "LBN", km: 58, arrivalMins: 164, departureMins: 164, dwellMin: 0 },
      { stationCode: "WL", km: 68, arrivalMins: 176, departureMins: 176, dwellMin: 0 },
      { stationCode: "KCG", km: 76, arrivalMins: 188, departureMins: 191, dwellMin: 3 },
      { stationCode: "NDKD", km: 94, arrivalMins: 209, departureMins: 209, dwellMin: 0 },
      { stationCode: "NDL", km: 120, arrivalMins: 235, departureMins: 235, dwellMin: 0 },
    ],
  },
  {
    trainId: "R-12434",
    serviceNumber: "12434",
    trainName: "Rajdhani Express",
    trainType: "Rajdhani",
    priorityClass: 1,
    direction: "DOWN",
    stops: [
      { stationCode: "SEC", km: 40, arrivalMins: 165, departureMins: 165, dwellMin: 0 },
      { stationCode: "LBN", km: 58, arrivalMins: 188, departureMins: 188, dwellMin: 0 },
      { stationCode: "WL", km: 68, arrivalMins: 198, departureMins: 198, dwellMin: 0 },
      { stationCode: "KCG", km: 76, arrivalMins: 210, departureMins: 212, dwellMin: 2 },
      { stationCode: "NDKD", km: 94, arrivalMins: 232, departureMins: 232, dwellMin: 0 },
      { stationCode: "NDL", km: 120, arrivalMins: 258, departureMins: 258, dwellMin: 0 },
    ],
  },
  {
    trainId: "AB-12076",
    serviceNumber: "12076",
    trainName: "Amrit Bharat Express",
    trainType: "Amrit Bharat",
    priorityClass: 2,
    direction: "DOWN",
    stops: [
      { stationCode: "SEC", km: 40, arrivalMins: 195, departureMins: 195, dwellMin: 0 },
      { stationCode: "LBN", km: 58, arrivalMins: 222, departureMins: 222, dwellMin: 0 },
      { stationCode: "WL", km: 68, arrivalMins: 235, departureMins: 235, dwellMin: 0 },
      { stationCode: "KCG", km: 76, arrivalMins: 248, departureMins: 252, dwellMin: 4 },
      { stationCode: "NDKD", km: 94, arrivalMins: 276, departureMins: 276, dwellMin: 0 },
      { stationCode: "NDL", km: 120, arrivalMins: 306, departureMins: 306, dwellMin: 0 },
    ],
  },
  {
    trainId: "S-12009",
    serviceNumber: "12009",
    trainName: "Shatabdi Express",
    trainType: "Shatabdi",
    priorityClass: 1,
    direction: "UP",
    stops: [
      { stationCode: "NDL", km: 120, arrivalMins: 210, departureMins: 210, dwellMin: 0 },
      { stationCode: "NDKD", km: 94, arrivalMins: 232, departureMins: 232, dwellMin: 0 },
      { stationCode: "KCG", km: 76, arrivalMins: 246, departureMins: 248, dwellMin: 2 },
      { stationCode: "WL", km: 68, arrivalMins: 258, departureMins: 258, dwellMin: 0 },
      { stationCode: "LBN", km: 58, arrivalMins: 270, departureMins: 270, dwellMin: 0 },
      { stationCode: "SEC", km: 40, arrivalMins: 292, departureMins: 292, dwellMin: 0 },
    ],
  },
  {
    trainId: "SF-12724",
    serviceNumber: "12724",
    trainName: "Telangana Superfast",
    trainType: "Superfast Express",
    priorityClass: 2,
    direction: "UP",
    stops: [
      { stationCode: "NDL", km: 120, arrivalMins: 280, departureMins: 280, dwellMin: 0 },
      { stationCode: "NDKD", km: 94, arrivalMins: 308, departureMins: 308, dwellMin: 0 },
      { stationCode: "KCG", km: 76, arrivalMins: 326, departureMins: 330, dwellMin: 4 },
      { stationCode: "WL", km: 68, arrivalMins: 342, departureMins: 342, dwellMin: 0 },
      { stationCode: "LBN", km: 58, arrivalMins: 358, departureMins: 358, dwellMin: 0 },
      { stationCode: "SEC", km: 40, arrivalMins: 384, departureMins: 384, dwellMin: 0 },
    ],
  },
  {
    trainId: "EXP-17015",
    serviceNumber: "17015",
    trainName: "Visakha Express",
    trainType: "Express Passenger",
    priorityClass: 3,
    direction: "DOWN",
    stops: [
      { stationCode: "SEC", km: 40, arrivalMins: 310, departureMins: 310, dwellMin: 0 },
      { stationCode: "LBN", km: 58, arrivalMins: 340, departureMins: 342, dwellMin: 2 },
      { stationCode: "WL", km: 68, arrivalMins: 358, departureMins: 362, dwellMin: 4 },
      { stationCode: "KCG", km: 76, arrivalMins: 378, departureMins: 382, dwellMin: 4 },
      { stationCode: "NDKD", km: 94, arrivalMins: 410, departureMins: 412, dwellMin: 2 },
      { stationCode: "NDL", km: 120, arrivalMins: 445, departureMins: 445, dwellMin: 0 },
    ],
  },
  {
    trainId: "EXP-12760",
    serviceNumber: "12760",
    trainName: "Charminar Express",
    trainType: "Superfast Express",
    priorityClass: 2,
    direction: "UP",
    stops: [
      { stationCode: "NDL", km: 120, arrivalMins: 370, departureMins: 370, dwellMin: 0 },
      { stationCode: "NDKD", km: 94, arrivalMins: 398, departureMins: 400, dwellMin: 2 },
      { stationCode: "KCG", km: 76, arrivalMins: 418, departureMins: 422, dwellMin: 4 },
      { stationCode: "WL", km: 68, arrivalMins: 434, departureMins: 436, dwellMin: 2 },
      { stationCode: "LBN", km: 58, arrivalMins: 452, departureMins: 452, dwellMin: 0 },
      { stationCode: "SEC", km: 40, arrivalMins: 478, departureMins: 478, dwellMin: 0 },
    ],
  },
  {
    trainId: "VB-20834",
    serviceNumber: "20834",
    trainName: "Vande Bharat Return",
    trainType: "Vande Bharat",
    priorityClass: 1,
    direction: "UP",
    stops: [
      { stationCode: "NDL", km: 120, arrivalMins: 420, departureMins: 420, dwellMin: 0 },
      { stationCode: "NDKD", km: 94, arrivalMins: 442, departureMins: 442, dwellMin: 0 },
      { stationCode: "KCG", km: 76, arrivalMins: 456, departureMins: 458, dwellMin: 2 },
      { stationCode: "WL", km: 68, arrivalMins: 468, departureMins: 468, dwellMin: 0 },
      { stationCode: "LBN", km: 58, arrivalMins: 480, departureMins: 480, dwellMin: 0 },
      { stationCode: "SEC", km: 40, arrivalMins: 502, departureMins: 502, dwellMin: 0 },
    ],
  },
];

// -------------------------------------------------------------
// SOURCE 5: GOODS FORECAST (FOIS) — 3 Scheduled Freight Movements
// -------------------------------------------------------------
export const CANONICAL_GOODS_FORECAST: GoodsMovementForecast[] = [
  {
    rakeId: "FRT-G4217",
    cargoType: "Container (CONCOR)",
    originStation: "SEC (Container Depot)",
    destinationStation: "NDL Yard",
    direction: "DOWN",
    targetWindowStartMins: 280, // 04:40
    targetWindowEndMins: 410,   // 06:50
    speedKmph: 55,
    loopLineStablingAllowed: true,
    sourceSystem: "FOIS (Freight Operations Information System)",
  },
  {
    rakeId: "FRT-CL8902",
    cargoType: "Coal (NTPC)",
    originStation: "WL Siding",
    destinationStation: "SEC Thermal",
    direction: "UP",
    targetWindowStartMins: 110, // 01:50
    targetWindowEndMins: 220,   // 03:40
    speedKmph: 45,
    loopLineStablingAllowed: true,
    sourceSystem: "FOIS (Freight Operations Information System)",
  },
  {
    rakeId: "FRT-ST5511",
    cargoType: "Steel (SAIL)",
    originStation: "NDKD Yard",
    destinationStation: "NDL Main",
    direction: "DOWN",
    targetWindowStartMins: 360, // 06:00
    targetWindowEndMins: 450,   // 07:30
    speedKmph: 50,
    loopLineStablingAllowed: false,
    sourceSystem: "FOIS (Freight Operations Information System)",
  },
];

// -------------------------------------------------------------
// SOURCE 6: BLOCK CORRIDORS (BDMS Sections) — 6 Available Sections
// -------------------------------------------------------------
export const CANONICAL_BLOCK_CORRIDORS: BlockCorridorSection[] = [
  {
    sectionId: "SEC-NDL-BLK-01",
    name: "SEC - KZJ Section",
    kmStart: 0,
    kmEnd: 32,
    lines: ["UP", "DOWN"],
    crossoverKm: [12, 24],
    tractionFeederPost: "FP-SEC-01",
    stationInterlockings: ["SEC", "CHZ", "BG"],
    maxDailyBlockWindowMin: 120,
    nominalOverheadMinutes: { isolation: 10, earthing: 10, transit: 5, restoration: 5 },
  },
  {
    sectionId: "SEC-NDL-BLK-02",
    name: "KZJ - WL Section",
    kmStart: 32,
    kmEnd: 68,
    lines: ["UP", "DOWN"],
    crossoverKm: [42, 58],
    tractionFeederPost: "FP-KZJ-02",
    stationInterlockings: ["KZJ", "LBN", "WL"],
    maxDailyBlockWindowMin: 140,
    nominalOverheadMinutes: { isolation: 10, earthing: 10, transit: 5, restoration: 5 },
  },
  {
    sectionId: "SEC-NDL-BLK-03",
    name: "WL - NDKD Section (Flagship Corridor)",
    kmStart: 68,
    kmEnd: 94,
    lines: ["UP", "DOWN"],
    crossoverKm: [76, 86],
    tractionFeederPost: "FP-WL-03",
    stationInterlockings: ["WL", "KCG", "NDKD"],
    maxDailyBlockWindowMin: 180,
    nominalOverheadMinutes: { isolation: 10, earthing: 10, transit: 5, restoration: 5 },
  },
  {
    sectionId: "SEC-NDL-BLK-04",
    name: "NDKD - NDL Section",
    kmStart: 94,
    kmEnd: 128,
    lines: ["UP", "DOWN"],
    crossoverKm: [108, 120],
    tractionFeederPost: "FP-NDL-04",
    stationInterlockings: ["NDKD", "GID", "NDL"],
    maxDailyBlockWindowMin: 150,
    nominalOverheadMinutes: { isolation: 10, earthing: 10, transit: 5, restoration: 5 },
  },
  {
    sectionId: "SEC-NDL-BLK-05",
    name: "KCG Crossover Interlocking Area",
    kmStart: 74,
    kmEnd: 78,
    lines: ["UP", "DOWN"],
    crossoverKm: [75.8, 76.4],
    tractionFeederPost: "FP-WL-03",
    stationInterlockings: ["KCG"],
    maxDailyBlockWindowMin: 90,
    nominalOverheadMinutes: { isolation: 10, earthing: 10, transit: 5, restoration: 5 },
  },
  {
    sectionId: "SEC-NDL-BLK-06",
    name: "WL Yard & Goods Loop Section",
    kmStart: 66,
    kmEnd: 70,
    lines: ["UP", "DOWN"],
    crossoverKm: [68.2],
    tractionFeederPost: "FP-KZJ-02",
    stationInterlockings: ["WL"],
    maxDailyBlockWindowMin: 110,
    nominalOverheadMinutes: { isolation: 10, earthing: 10, transit: 5, restoration: 5 },
  },
];
